### PR TITLE
Auto-switch default payment method to google pay when power menu is open

### PR DESCRIPTION
**Pull request by Philip2809**
If you need to use multiple NFC apps where it automatically changes your "default payment method", as in the case of Card Emulator, switch the "default payment method" back to Google Pay when the power menu is opened so that the quick wallet can be used

### CODE REVIEW

**Comment by KieronQuinn** [comment]
Few things:
- This should probably be an option, or check if the user's Quick Access Wallet is set to Google Wallet. I have no idea if any OEM made their own, but they may not be using Google Wallet as a result.
- The user can [disable the Quick Access Wallet](https://github.com/KieronQuinn/ClassicPowerMenu/blob/fe566cf30f4539f84887c78d8f388a38b8fe69b7/app/src/main/java/com/kieronquinn/app/classicpowermenu/components/settings/Settings.kt#L27), in which case this shouldn't be run when they open the power menu.
- Please wrap the use of Settings.Secure.putString in a try/catch since there's a possibility either the permission granting in the root service may either fail, or the permission may have been revoked while the app is running. This is not a fatal error, so it shouldn't crash the app.

Once these are resolved, I'll merge this 👍

**Comment by Philip2809** [comment]
Alright, sounds good, will work these points

**Comment by Philip2809** [comment]
My ideas to fix these few things was to add an option in the Quick Access Wallet settings to if open set the default to an app the user can select from a list. I have tried to look into how to get this list of payment supported apps; however I can only manage to get the list of that use the `HOST_APDU_SERVICE`, and this includes both `CATEGORY_PAYMENT` and `CATEGORY_OTHER`. The only ones available for default payment method is `CATEGORY_PAYMENT`, but the function the android settings app uses is not available when I write the code. It uses `getServices` from `CardEmulation`, this function is defined but I can't use it!? Sadly I can't find a method to filter what services uses `CATEGORY_PAYMENT` and `CATEGORY_OTHER`. Currently I get the services with `HOST_APDU_SERVICE`
```
val intent = Intent("android.nfc.cardemulation.action.HOST_APDU_SERVICE").addCategory(Intent.CATEGORY_DEFAULT)
val resolveInfoList = packageManager!!.queryIntentServices(intent, PackageManager.MATCH_DEFAULT_ONLY)
```
Any tought on this, would it be ok to have a list with applications that may not work? There is very little information on this topic sadly..

**Comment by Philip2809** [comment]
Added these options, by default its turned off:
Screenshot_20240822-221430
What icons should it have?
When you open the select service view: (if there is any matching services, selected one is highlighted, by default none is)
Screenshot_20240822-221534
If there is not any matching services: (simulated by passing an empty list)
Screenshot_20240822-221423

It says my phone has 4 services for this, two are for payment (Card Emulator and Google Pay), the other two is "CATEGORY_OTHER". I didn't find a way to sort these out sadly, but if you would select it and then run the command, the android settings default contactless payment looks like this:
Screenshot_20240822-221600

**Comment by KieronQuinn** [comment]
All good except that included redundant class - once that's gone I'll merge it :)

**Comment by Philip2809** [comment]
Sorry, redundant class, what do you mean?

**Comment by KieronQuinn** [comment]
Merged, I'll run a build with the changes shortly

**Comment by Philip2809** [comment]
Perfect! Thank you for merging, will try to see if there is anything else I can work on, as I really like this project and want to develop more for android!

**Comment by KieronQuinn** [comment]
Included in 1.8, build took a while since the codebase is ancient and needed some serious refactoring to work with predictive back

**Pull request merged**
