### PR TITLE
Fix loyalty cards by adding a google signin option

### PR DESCRIPTION
**Pull request by Philip2809**
Fix loyaltycards by adding an option to sign in to google. Code heavily inspired from https://github.com/KieronQuinn/SmartspacerPlugins

Fixes:
- Login to google
- Load loyalty cards by pressing sync button
- Rearrange loyaltycards then press the eye icon now works
- Logout and delete stored wallet and account data

Todo:
- ~~Backup rules so only preferences are backed up, not encrypted ones~~
- ~~Cache in sync call~~
- ~~Add screenshots~~
- ~~Datamatrix code takes up full width~~ (Will open a separate issue and fix this later)

Settings:
Untitled
Info and then the google embedded login screen
Untitled-1
Press sync button to get the cards:
Untitled
Hide and rearrange
Untitled-1
Untitled

### CODE REVIEW

**Comment by Philip2809** [comment]
@KieronQuinn Do you have any experience with how the backup rules work and how to make it only backup certain preferences? Also, do you want me to rewrite the LoyaltyCard class or is the quick mapping I have done good enough?

**Comment by KieronQuinn** [comment]
- I usually disable backup entirely and implement my own, there's probably a way to exclude an entire preference file though.
- The mapping looks fine
- I think manual should be ok, so long as it's made clear in the app. There's no way to make it instant, so there'd always be a wait anyway so most people would likely open the app to trigger a manual refresh.

**Comment by Philip2809** [comment]
About the backups, is it really even necessary for this app? There is not really a lot of settings and wouldn't is mess with the fact that it was setup on one phone but when backup is restored the module or accessibility service is not turned on?

**Comment by KieronQuinn** [comment]
Yeah it's usually not top priority which is why there's no custom backup/restore currently implemented. We can probably just disable backups entirely, and if there's enough demand I'll just port the backup/restore engine from Smartspacer.

**Comment by Philip2809** [comment]
I managed to make the backups work pretty fast, thought it was going to be a lot harder, it was actually pretty easy. I do not backup:
- encrypted_shared_prefs.xml
- room_encrypted_shared_prefs.xml
- all databases
- webview data (to remove the cookies)
Everything else is backed up and it works very good actually, even the order is remembered! I will add a text to press the sync button and add the cache stuff to the sync call, after that I feel I am done, anything else I need to do?

**Comment by KieronQuinn** [comment]
I think that's everything, I'll get it merged once that's done, test it on my devices, and run a build. I may also decrease the target SDK again to see if it fixes #143

**Comment by Philip2809** [comment]
I think I am ready now, fixed caching and a bug where if the loyalty card have no image the app crashes. It think I have covered all grounds with my testing, you can add and remove cards in the wallet app, sync and CPM reflects the changes.

**Comment by KieronQuinn** [comment]
Pushed a few fixes for UI related issues found during testing, it's ready to merge now. Thanks for your work!

**Pull request merged**
